spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/customer-service?createDatabaseIfNotExist=true
    username: root
    password: senha432
  jackson:
    default-property-inclusion: non_null